// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/download/http.go

// Package download is a generated GoMock package.
package download

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHttpRequester is a mock of HttpRequester interface.
type MockHttpRequester struct {
	ctrl     *gomock.Controller
	recorder *MockHttpRequesterMockRecorder
}

// MockHttpRequesterMockRecorder is the mock recorder for MockHttpRequester.
type MockHttpRequesterMockRecorder struct {
	mock *MockHttpRequester
}

// NewMockHttpRequester creates a new mock instance.
func NewMockHttpRequester(ctrl *gomock.Controller) *MockHttpRequester {
	mock := &MockHttpRequester{ctrl: ctrl}
	mock.recorder = &MockHttpRequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpRequester) EXPECT() *MockHttpRequesterMockRecorder {
	return m.recorder
}

// GetContent mocks base method.
func (m *MockHttpRequester) GetContent(url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent", url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContent indicates an expected call of GetContent.
func (mr *MockHttpRequesterMockRecorder) GetContent(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockHttpRequester)(nil).GetContent), url)
}
