name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v cmd/...

      - name: Run go vet
        run: go vet cmd/...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint cmd/...

      - name: Run tests
        run: go test -race -vet=off ./...
